name: Todo Service Deployment

on:
  push:
    branches:
    - stage

jobs:
  darkube_build_todo-service_bigdeliali3-todo-staging_hamravesh-c13:
    container:
      image: hamravesh/darkube-cli:v1.1
      options: --user root
    env:
      IMAGE_NAME: registry.hamdocker.ir/bigdeliali3/todo-service
    runs-on: ubuntu-latest
    steps:
    - name: checkout commit
      uses: actions/checkout@v4
    - name: darkube-cli build & push
      run: 'darkube build --push -t $IMAGE_NAME:${GITHUB_SHA:0:7} -t $IMAGE_NAME:${GITHUB_REF_NAME}
        --docker-auth-config ${{secrets.DOCKER_AUTH_CONFIG}} --workdir . --file ./Dockerfile.stage
        --build-context . '
  darkube_deploy_todo-service_bigdeliali3-todo-staging_hamravesh-c13:
    container: hamravesh/darkube-cli:v1.1
    needs: darkube_build_todo-service_bigdeliali3-todo-staging_hamravesh-c13
    runs-on: ubuntu-latest
    steps:
    - name: darkube-cli deploy
      run: darkube deploy --token ${{secrets.DEPLOY_TOKEN_TODO_SERVICE_BIGDELIALI3_TODO_STAGING_HAMRAVESH_C13}}
        --app-id ${{secrets.APP_ID_TODO_SERVICE_BIGDELIALI3_TODO_STAGING_HAMRAVESH_C13}}
        --image-tag ${GITHUB_SHA:0:7} --job-id ${GITHUB_RUN_ID}
